version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6
    steps:
    - checkout
    - run:
        name: Setup testing environment
        command: |
          make install-dev
    - run:
        name: Run tests and measure coverage
        command: |
          make coverage
    - store_artifacts:
        path: htmlcov
    - run:
        name: verify git tag vs. version
        command: |
          python3 -m venv venv
          . venv/bin/activate
          python setup.py verify
    - run:
        name: init .pypirc
        command: |
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username = levlaz" >> ~/.pypirc
          echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
workflows:
  version: 2
  workflow:
    jobs:
    - build
